# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Which
version:      0.01_02
version_from: lib/Module/Which.pm
installdirs:  site
requires:
    GetOpt::Long:                  0
    Module::Find:                  0
    Pod::Usage:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
