--- #YAML:1.0
name:                Module-Which
version:             0.0207
abstract:            Finds out which version of Perl modules are installed
license:             perl
author:              
    - A. R. Ferreira <ferreira@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Find:                    0
    File::Glob:                    0
    File::Spec:                    0.8
    File::Spec::Unix:              0
    Getopt::Long:                  0
    Pod::Usage:                    0
    String::Truncate:              0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3

recommends:
    Test::Pod:                     1.18
    Term::Size::Any:               0
no_index:
    file:
        - inc/Module/Downgrade.pm
