---
# http://module-build.sourceforge.net/META-spec.html
name:         Module-Which
version:      0.01_03
version_from: lib/Module/Which.pm
author:
  - Adriano Ferreira <ferreira@cpan.org>
license: perl
requires:
    GetOpt::Long:                  0
    Module::Find:                  0
    Pod::Usage:                    0
    Test::More:                    0
recommends:
    Test::Pod:                     1.00
installdirs:  site

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
